export const IS_CHECK_SAGA_NO_PAYLOAD = "IS_CHECK_SAGA_NO_PAYLOAD";
export const IS_CHECK_SAGA_NO_PAYLOAD_REQ = "IS_CHECK_SAGA_NO_PAYLOAD_REQ";

export const IS_CHECK_SAGA_HAS_PAYLOAD = "IS_CHECK_SAGA_HAS_PAYLOAD";
export const IS_CHECK_SAGA_HAS_PAYLOAD_REQ = "IS_CHECK_SAGA_HAS_PAYLOAD_REQ";